name: CI

on:
  push:
  pull_request:

jobs:

  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: py39-test
        - macos: py310-test
        - windows: py311-test

  # Automatically tag commits to main with the latest calendar version. Note that
  # this does not currently support two versions in the same day, but if this is
  # needed exceptionally, it is possible to manually push a tag.
  tag:
    needs: tests
    name: Tag latest commit to main using calendar version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get tag name from date
        id: tag_name
        run: echo "version=0.$(date +'%Y.%m.%d.%H.%M.%S')" > $GITHUB_OUTPUT
      - name: Check tag
        run: echo ${{ steps.tag_name.outputs.version }}
      - name: Create tag
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.tag_name.outputs.version }}

  publish:
    needs: tag
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      # The usual tag condition for uploading to PyPI doesn't work because the tag has just been
      # created, but we know we can run on any push to main since this is the same condition for
      # making a tag above.  
      upload_to_pypi: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
