name: Auto-update IERS tables

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-iers:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    name: Auto-update IERS tables
    runs-on: ubuntu-latest
    if: github.repository == 'astrofrog/astropy-iers-data'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download latest IERS files
      run: ./update_data.sh
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add astropy_iers_data/data
        if ! git diff --cached --exit-code; then
          git commit -m "Update IERS Earth rotation and leap second tables"
        fi
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: update-iers
        branch-suffix: timestamp
        delete-branch: true
        title: Update IERS Earth rotation and leap second tables
        body: |
          This is an automated update of the IERS Earth rotation and leap second tables.

